import jsPDF from "jspdf";
import type { Report } from "@/components/ScanReport";

async function urlToDataUrl(url: string): Promise<string | null> {
  try {
    const r = await fetch(url);
    const b = await r.blob();
    return await new Promise((res) => {
      const fr = new FileReader();
      fr.onload = () => res(fr.result as string);
      fr.onerror = () => res(null);
      fr.readAsDataURL(b);
    });
  } catch {
    return null;
  }
}

export async function exportReportPdf(report: Report, image: string | null) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 40;
  let y = M;

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, W, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("BioScan AI Report", M, 42);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(new Date().toLocaleString(), W - M, 42, { align: "right" });
  y = 90;

  // Image
  if (image) {
    const dataUrl = image.startsWith("data:") ? image : await urlToDataUrl(image);
    if (dataUrl) {
      try {
        doc.addImage(dataUrl, "JPEG", M, y, 200, 200, undefined, "FAST");
      } catch {}
    }
  }

  // Title block
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(report.commonName, M + 220, y + 24);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(report.scientificName, M + 220, y + 42);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(40);
  doc.text(`Kind: ${report.kind}   Confidence: ${Math.round(report.confidence)}%   Health: ${report.healthScore}/100`, M + 220, y + 62);
  const sumLines = doc.splitTextToSize(report.summary || "", W - (M + 220) - M);
  doc.text(sumLines, M + 220, y + 82);
  y += 220;

  const ensureSpace = (h: number) => {
    if (y + h > H - M) { doc.addPage(); y = M; }
  };

  const section = (title: string) => {
    ensureSpace(30);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(15, 23, 42);
    doc.text(title, M, y);
    y += 6;
    doc.setDrawColor(200);
    doc.line(M, y, W - M, y);
    y += 14;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(40);
  };

  const writePara = (label: string, value: string) => {
    if (!value) return;
    const lines = doc.splitTextToSize(`${label}: ${value}`, W - 2 * M);
    ensureSpace(lines.length * 12 + 6);
    doc.text(lines, M, y);
    y += lines.length * 12 + 4;
  };

  if (report.diseases?.length) {
    section("Diagnosis");
    report.diseases.forEach((d, i) => {
      ensureSpace(20);
      doc.setFont("helvetica", "bold");
      doc.text(`${i + 1}. ${d.name}  (${d.severity})`, M, y);
      y += 14;
      doc.setFont("helvetica", "normal");
      writePara("Symptoms", d.symptoms);
      writePara("Causes", d.causes);
      writePara("Treatment", d.treatment);
      writePara("Prevention", d.prevention);
      if (d.recoveryDays) writePara("Recovery", d.recoveryDays);
      y += 6;
    });
  }

  section("Care Guide");
  writePara("Light", report.care?.light || "");
  writePara("Water", report.care?.water || "");
  writePara("Temperature", report.care?.temperature || "");
  writePara(report.kind === "fish" ? "Feeding" : "Fertilizer", report.care?.food || "");
  writePara("Environment", report.care?.environment || "");
  (report.care?.extras || []).forEach((t) => writePara("Tip", t));

  if (report.funFacts?.length) {
    section("Did you know?");
    report.funFacts.forEach((f) => writePara("•", f));
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("Generated by BioScan AI — Identifications are for guidance.", M, H - 20);
    doc.text(`${i} / ${pageCount}`, W - M, H - 20, { align: "right" });
  }

  const safe = report.commonName.replace(/[^a-z0-9]+/gi, "_").slice(0, 40) || "scan";
  doc.save(`bioscan-${safe}.pdf`);
}